### ISSUE TITLE
Steam Deck/Linux Support?

### ISSUE THREAD

**Issue by BrochachoTheBro** [X-Hax/SA-Mod-Manager#107]
Any word on Steam Deck and Linux support? HamStar had a great guide for getting the old SADX Mod Manager running on Deck, but that's since gone out the window now that the new SA Mod Manager took over and the old SA2 Mod Manager got deprecated.
I tried using Bottles in a similar fashion to setting Hedge Mod Manager up, but I couldn't download the dependencies like any of the dotnets, ProtonTricks wouldn't recognize the non-Steam shortcut to select.

**Comment by PiKeyAr** [comment]
Officially there's no support for Linux or the Steam Deck, and there probably won't be in the observable future due to how the game, the loader and the manager are programmed. However, it is possible to run the new Manager and the game on the Steam Deck, and there are updated tutorials such as [this one](https://gamebanana.com/tuts/16934). While we try to not break Linux support on purpose, we cannot guarantee that unofficial tutorials will work forever (or at all). Ultimately Steam Deck and Linux compatibility is at the mercy of Proton. It's not ideal but it's probably going to get better. 


We're doing some minor work on the Loader and Manager's side that may improve compatibility with Linux as well, such as getting rid of the Windows Media Player dependency.

**Comment by ItsEasyActually** [comment]
As PkR said, there is bare bones support and we do our best to improve where there may be some issues, but that's all we can offer at this time.

In short, native Linux support is not planned at this time as it would require another rewrite to the system we use for the UI (WPF is Windows only). While it's still under consideration, there are no current plans to move to Avalonia or something else that would have native Linux Support for the Manager itself. 

Additionally, use the guide PkR linked. It was updated within a couple of weeks of the initial launch for the SA Mod Manager. We also dealt with reports of Linux/Steam Deck issues when we added SA2 support and have fixed what we could from what was reported.

**Comment by BrochachoTheBro** [comment]
The guide PkR linked was the one I was referencing. And from my usage, using the SA Mod Manager via the SADX Mod Installer method doesn't support SA2 (installing mods and changing configs didn't work). I might have potentially done something wrong when trying to transition from SA2MM to SAMM, but there wasn't a guide at the time.

Also to preface I'm not expecting native Linux support or anything, was just asking about compatibility.
