### ISSUE TITLE
The entire window stretches and breaks on my AMD graphics card

### ISSUE THREAD

**Issue by Rebirthdd** [X-Hax/SA-Mod-Manager#150]
When resizing the window or even getting popups, the windrow stretches instead of scaling like a natural window

1. Go to corner
2. Click on the corner
3. S t r e t c h
4. the window is broken

also after it is stretched, my mouse no longer works and I have to restart the application. Popups seem to not function properly at all for me as I cannot edit any mod configs.

**Expected behavior**
the window should just work?

**Screenshots**
![Screenshot 2024-06-05 031000](https://github.com/X-Hax/SA-Mod-Manager/assets/171780326/fd341cb6-c11d-4c04-8136-5ada6e0aeff9)
![Screenshot 2024-06-05 032546](https://github.com/X-Hax/SA-Mod-Manager/assets/171780326/b0d0bde3-9b51-42ec-b6ff-aebc712494d9)

**Demonstration**
https://youtu.be/-iY45X2jOcY

**Desktop:**
 - OS: Windows 11
 - Version 1.29 & before

**Comment by PiKeyAr** [comment]
For the record, I have an AMD card and I'm not getting any of this.

**Comment by ItsEasyActually** [comment]
This isn't an issue with AMD. After researching, the closest reports I could find to your issue reference Alienware. 

If you happen to be using an Alienware PC and/or have Alienware's Nahimic services installed, that's quite likely the cause of this. You can follow the steps [here](https://github.com/dotnet/wpf/issues/5708#issuecomment-974635171) to get the Mod Manager blacklisted and it should restore normal behavior.

If you don't have anything Alienware and don't have the Nahimic/Alienware services installed, the issue is still with your system unfortunately. We have several users who do use AMD, one of whom I know has a PC that could fail any day now, and they have not had this issue.

**Comment by Rebirthdd** [comment]
> This isn't an issue with AMD. After researching, the closest reports I could find to your issue reference Alienware.
> 
> If you happen to be using an Alienware PC and/or have Alienware's Nahimic services installed, that's quite likely the cause of this. You can follow the steps [here](https://github.com/dotnet/wpf/issues/5708#issuecomment-974635171) to get the Mod Manager blacklisted and it should restore normal behavior.
> 
> If you don't have anything Alienware and don't have the Nahimic/Alienware services installed, the issue is still with your system unfortunately. We have several users who do use AMD, one of whom I know has a PC that could fail any day now, and they have not had this issue.

I have nothing alienware, but I have noticed that the issue only occurs only after I scroll in any config
