### ISSUE TITLE
Mods Downloading to Incorrect Folder

### ISSUE THREAD

**Issue by C-Rex1** [X-Hax/SA-Mod-Manager#156]
**Issue**
Whenever I try downloading mods from GameBanana, the mod manager will always download them to the SADX/mods folder, even if they are SA2 mods. This means I have to manually relocate them every time. Modloader appears to be installed correctly.

**Expected behavior**
The mod should download to the folder for its respective game, instead of the SADX mods folder, by default.

**Desktop:**
 - OS: Windows 11
 - Version: 23H2

**Comment by Sora-yx** [comment]
That was an issue on previous versions but that should be fixed since.

1) Make sure you are on the last Manager version (currently 1.2.9)
2) In the Manager Config tab, re set the game directory for both Adventure games by clicking here:
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/50106301/793f7636-17ee-4a68-b037-e7fdeaaf7fce)
3) Save, restart the program and try again

**Comment by Sora-yx** [comment]
After further testing, this is an issue with Gamebanana having the one click install leading to SADX for SA2 mods, I warned them so they should fix it soon. Closing this as it's not Manager related.
