### ISSUE TITLE
Sonic Adventure 2 Not Saving in Game Directory

### ISSUE THREAD

**Issue by Blade194** [X-Hax/SA-Mod-Manager#160]
Whenever I try to add SA2 to the game directory the game disappears whenever I close the app and all my mods get disabled

The first Pic is when I put the mod in the directory
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/149477796/dd9dbb1c-8918-4c2e-a7e4-cad5c2dee838)

This 2nd one when I close out of the SA mod manager and go back in
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/149477796/77d2e20c-a644-4636-8bc9-7e6528ba70f0)

**Comment by Sora-yx** [comment]
Note that we don't officially support pirated copy, but either way, I cannot reproduce your issue, even with a set up when the games aren't detected, if I add SADX and SA2 manually, they are saved fine for me.

You can try to delete the SAManager folder in AppData -> Local and try again, see if maybe that fixes your issue, but otherwise, unless you can show me a specific way that I can reproduce this, there is nothing we can do.
