### ISSUE TITLE
SA2's executable isn't detected despite being set to the correct directory, and setting SA2's game directory automatically switches the config to SA1

### ISSUE THREAD

**Issue by soupini** [X-Hax/SA-Mod-Manager#184]
I might be missing something, but I can't seem to get the mod manager to detect Sonic Adventure 2's executable. The "Save & Play" option is grayed out, and clicking Install Mod Loader displays the "Failed to detect game path" message (it even says that sonic.exe isn't detected, despite the fact that I don't think SA2's executable should be called that).

Just for context, I installed the mod manager through opening the old SA2 Mod Loader and using the feature where you auto-install SA Mod Manager.

![Capture](https://github.com/user-attachments/assets/dda8e596-2cb7-4f05-b2c8-b222e6e8a730)

I'm on Windows 10, and I'm using version 1.2.10.

**Comment by Sora-yx** [comment]
Do you have sonic2app.exe present in the game folder? If you renamed it, it won't work.

**Comment by Iggyminious** [comment]
> Do you have sonic2app.exe present in the game folder? If you renamed it, it won't work.

Actually, a while back I changed the name of sonic2app.exe to Launcher.exe (and added a .bak to the original Launcher.exe) in order to fix some graphical issues. Changing the name back to sonic2app.exe solved the installation issue for me, though for some reason I remember it not working when I tried it earlier.
