### ISSUE TITLE
"You must install .NET Desktop Runtime to run this application." (LINUX)

### ISSUE THREAD

**Issue by supervitu64** [X-Hax/SA-Mod-Manager#258]
**Describe the bug**.
The manager will not start on Linux, even though i installed all the required runtimes

**To Reproduce**
1. Download the mod manager and rename it to Launcher
2. Start SA2
3. Manager refuses to aknowledge .NET 8 is installed

**Expected behavior**
The loader actually starts

**Screenshots**
![image](https://github.com/user-attachments/assets/6b6768e5-17db-42ea-86f0-d60305af6bec)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 22 Wilma

**Comment by ItsEasyActually** [comment]
The program is a Windows only program at this time. You have to run it with something that works as a Windows layer. If you already are, then the issue is with getting .NET installed on it.

You should also absolutely not replace the Launcher with the Mod Manager. It will cause issues when trying to update the Manager. If you want the game to boot through Steam and skip the native Launcher, add the launch option `-q` in Steam.

**Comment by antoineok** [comment]
The issue is that this popup can also show up with both x86 and x64 version of this dot net desktop version installed
