### ISSUE TITLE
Mod Manager is unable to delete profiles

### ISSUE THREAD

**Issue by TheGamingSiri** [X-Hax/SA-Mod-Manager#31]
SA Mod Manager is able to create profiles in a normal manner, but attempting to delete an existing profile will cause the program to crash.
P.S. Where are the profiles saved in the Sonic Adventure DX directory? I wasn't able to find them and so I wasn't able to test what removing them manually would do.

**Comment by TheGamingSiri** [comment]
Update: I tried to remove the profiles manually from SADX's appdata folder, but no dice. The program still sees them somehow, and attempting to delete them crashes the program.

**Comment by ItsEasyActually** [comment]
Profiles are able to be deleted per my recent testing without the manager crashing. You'll need to provide specifics on whatever you're doing that's causing the issue. Do note that you **cannot** delete the currently set profile (will look at making an indicator in the profile manager window, but the delete button is automatically disabled on the active profile in the profiles manager). The only reasons I can come up with as to why it's having issues is either a path issue or a permissions issue.

Profiles were also not made with the intention of deleting the files manually as they're saved in another file which is why it still "finds" them. I'll be updating the behavior on that front soon, so it will automatically clear any manually deleted profiles.

**Comment by Sora-yx** [comment]
We added some failsafe to handle cases of profile deleted manually as well as prevent crashing if it fails to delete the file, but there's not much more we can do, nobody else is having a similar issue and it works fine on our side.
