### ISSUE TITLE
Issues during Profile Creation

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SA-Mod-Manager#52]
There have been several reports of issues regarding the program crashing sometime in/after profile creation. It seems to result in invalid profile data. Deleting the SAManager's local folder fixes the issue, but we don't know the exact cause of it at the moment. Ideally an investigation into why it even happens would be best, but it seems like it's a very hit or miss bug with an indeterminate cause. Below is also a proposals section with easier to use solutions than the current one.

**Current Solution:** Direct users to their Users/AppData/Local/SAManager folder and have them delete the SAManager folder and reopen the program. This has fixed the issue for every report so far.

If we can gather any data on the why, please report it to this issue so we can gather as much info as possible.

---
### Proposals
- Add a Reset Button for easy resetting of the app's overall data. This will likely be added regardless as a way to completely reset the app would be ideal.

**Comment by PiKeyAr** [comment]
Some ideas:


Wrap profile validation in try-catch. In the catch part, different things could be done depending on what's left of configuration data:


- Profiles list doesn't exist: Initialize a profiles list, scan the folder for profile JSON files and add them to the list.


- Profiles list and profile JSON files exist but the current profile ID is null: 1) Try to set the "Default" profile; 2) Check for profile JSON files and try to load the first found profile JSON file. If it fails, try the other profile JSON files. On success, set the current profile ID to the one that loaded successfully. If none of the profiles could be loaded, reset all profile data and start over.


- Currently selected profile JSON file doesn't exist: Same as above.


- Currently selected profile fails to load because the JSON file has invalid data: Same as above.


- No profile JSON files exist: reset all profile data and start over

**Comment by ItsEasyActually** [comment]
Going ahead and closing this. Profiles recently received an overhaul that should have resolved most issues.
