### ISSUE TITLE
Make SA Mod Manager compatible with Windows XP and Vista

### ISSUE THREAD

**Issue by DellM-79** [X-Hax/SA-Mod-Manager#87]
Since the 2004 SADX game is compatible with Windows XP, it would be great if you tried to backport it to XP and Vista.

**Comment by Sora-yx** [comment]
We don't plan to make the Manager working on XP, if people manage to make some tweaks to get it to work, then that's good, but there is currently no plan for official support.

If you wish to play SADX modded on PC [the legacy manager is made for that.](https://github.com/X-Hax/sadx-mod-loader/releases/download/Legacy/SADXModLoader.7z)

**Comment by PiKeyAr** [comment]
I would've tried to backport it, but because the new Manager is made in WPF and using .NET 7.0 it's unrealistic.

You can still use the legacy Manager with the latest Mod Loader on XP right now, in a bit of an awkward way - i.e. you have to update the loader DLL manually and delete the new Manager's folders, also you can't change any settings that were added after the new Mod Manager was released. No promises, but at some point I do want to update the legacy Manager so that you could use it with the latest Mod Loader and still be able to edit all new settings on XP.

**Comment by Sewer56** [comment]
> and using .NET 7.0 it's unrealistic.

Note: .NET 7 and above don't officially support Win 7 either.
It'll boot, and probably work for a bit, but there's bugs involving the Garbage Collector there, stuff will eventually break.
